src/PocketDungSite/PocketDungSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #добалвяем 
from django.conf.urls.static import static #добалвяем 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')), #добавляем путь для ckeditor
    path('wiki/', include('wiki.urls')),
    path('', include('visitka.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #добавляем 

#if settings.DEBUG: #добавляем 
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #добавляем
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #добавляем 

src/PocketDungSite/wiki/urls.py
from django.urls import path  
from . import views  
  
app_name = "wiki" #пространство имен для приложения wiki
urlpatterns = [  
    path("", views.index, name="index"),
    path("login/", views.login_wiki, name="login"),
    path("logout/", views.logout_wiki, name="logout"),
    path("media/materials/<str:filename>", views.secure_file, name="secure_file"),
    path("searh_results/", views.searh, name="search"),
    path("searh_results/<int:i_id>", views.result_search, name="result_search"),
    path("<str:ic_url>/", views.InfoChapterDetails, name="InfoChapterDetails"),
    path("<str:ic_url>/<str:iss_url>/", views.InfoSubSectionDetails, name="InfoSubSectionDetails"),
    path("<str:ic_url>/<str:iss_url>/<int:i_id>/", views.InfoDetails, name="InfoDetails"),
    path("<str:ic_url>/<str:iss_url>/<int:i_id>/materials/<str:m_id>/delete/", views.deleteMaterial, name="deleteMaterial"),
]

src/PocketDungSite/wiki/models.py
from django.db import models
from datetime import date
from datetime import datetime


#раздел информации на wiki, они будут в навигационной панели
class InfoChapter(models.Model):
    ic_name = models.CharField(verbose_name="Название раздела", max_length=300)
    ic_url = models.CharField(verbose_name="Название раздела в url (желательно на EU)", max_length=300)

    def __str__(self) -> str:
        return self.ic_name
    
    class Meta:
        verbose_name = "Раздел на сайте"
        verbose_name_plural = "Раздела на сайте"


#подразделы на сайте, у каждого раздела есть подразделы
#например раздед локации, подразделы (лес, река, шахты)
class InfoSubSection(models.Model):
    infoChapter = models.ForeignKey(InfoChapter, on_delete = models.CASCADE, verbose_name="Раздел информации на wiki")
    iss_name = models.CharField(verbose_name="Название подраздела", max_length=300)
    iss_url = models.CharField(verbose_name="Название подраздела в url (желательно на EU)", max_length=300)
    iss_description = models.TextField(verbose_name="Краткое опсание подраздела", blank=True)


    def __str__(self) -> str:
        return self.iss_name
    
    class Meta:
        verbose_name = "Подраздел на сайте"
        verbose_name_plural = "Подразделы на сайте"


#модель для самих статей о мире или о персонажах 
class Info(models.Model):
    infoSubSection = models.ForeignKey(InfoSubSection, on_delete = models.CASCADE, verbose_name="Подраздел информации на wiki")
    i_name = models.CharField(verbose_name="Название статьи", max_length=300)
    i_img = models.ImageField(verbose_name="Картинка для статьи", upload_to='info_images/', blank=True)
    i_date_creation = models.DateField(verbose_name="Дата создания статьи", default=date.today)
    i_text = models.TextField(verbose_name="Содержание статьи")

    def __str__(self) -> str:
        return self.i_name
    
    class Meta:
        verbose_name = "Статья на сайте"
        verbose_name_plural = "Статьи на сайте"

#материала к статтье, которые будут использоваться в игре (типо спрайта, звуки)
class Material(models.Model):
    info = models.ForeignKey(Info, on_delete = models.CASCADE, verbose_name="Статья на wiki")
    m_name = models.CharField(verbose_name="Название материала (например спрайт, анимаци ходьбы, звук)", max_length=300)
    m_date_add = models.DateField(verbose_name="Дата добавления", default=date.today)
    m_file = models.FileField(verbose_name="Файл материала к статье", upload_to='materials/')

    def __str__(self) -> str:
        return self.m_name
    
    class Meta:
        verbose_name = "Материал к статье на сайте"
        verbose_name_plural = "Материалы к статье на сайте"


#модель для логов дейтсвий с материалами на сайте
class LogMaterials(models.Model):
    m_name  = models.CharField(verbose_name="Название материала (например спрайт, анимаци ходьбы, звук)", max_length=300)
    ml_i_id = models.IntegerField(verbose_name="id статьи к которой идет материал")
    ml_action = models.CharField(verbose_name="Название действия с файлом", max_length=300)
    ml_date_add = models.DateTimeField(verbose_name="Дата", default=datetime.now)
    user_id = models.IntegerField(verbose_name="id пользователя")

src/PocketDungSite/wiki/forms.py
from django import forms
from .models import Material
from .models import Info


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ('m_name', 'm_file', )

src/PocketDungSite/wiki/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect #шорткат, чтобы не использовать HttpResponse и loader
from django.http import Http404 #для обработки ошибки 404
from .models import InfoChapter, InfoSubSection, Info, Material, LogMaterials
from datetime import datetime
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .forms import MaterialForm

#для пагинации
from django.core.paginator import Paginator

#для сохранения файла
from django.core.files.storage import default_storage

#имопртируем доумент для поиска 
from .documents import InfoDocument
from elasticsearch_dsl.query import MultiMatch

#для авторизации 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

#для отдачи файла 
from django.http import FileResponse

#логи django взаимодейтсиве пользователей
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import User


#Create your views here.


#получение всех разделов и подразделов wiki
def getAllInfoChapterWithSubSection() -> list:
    result = []
    InfoChapters = InfoChapter.objects.all()


    for ic in InfoChapters:
        subs = InfoSubSection.objects.filter(infoChapter__id = ic.id)
        subs_res = []

        for s in subs:
            subs_res.append(
                {
                    "iss_name": s.iss_name,
                    "iss_url": s.iss_url
                }
            )

        result.append(
            {
                "ic_name": ic.ic_name,
                "ic_url": ic.ic_url,
                "ic_subs": subs_res
            }
        )
    return result


#главная страница
@login_required
def index(request):
    #получение разделов сайта
    allInfoChapters = getAllInfoChapterWithSubSection()

    #получаем логи с админ панели
    logs = LogEntry.objects.all() 
    log_res = []

    for l in logs:

        if l.action_flag == 1:
            action = "добавлен"
        elif l.action_flag == 2:
            action = "изменён"
        elif l.action_flag == 3:
            action = "удалён"


        #тип объекта
        type="отсутсвует"
        if l.content_type_id == 4:
            type = "пользователь"
        elif l.content_type_id == 7:
            type = "материал"
        elif l.content_type_id == 8:
            type = "подраздел"
        elif l.content_type_id == 9:
            type = "раздел"
        elif l.content_type_id == 10:
            type = "статьи"
        
        #получаем пользователя, который сделал дейтсвие на сайте
        user = User.objects.filter(pk=l.user_id).first()


        log_res.append({
            "action_flag": action,
            "object_repr": l.object_repr,
            "type" : type,
            "date": l.action_time.strftime("%d.%m.%Y в %H:%M:%S"),
            "user_id": user
        })

    #получаем логи, которые связаны с материалами к статье
    logMaterials = LogMaterials.objects.order_by("-ml_date_add")
    logMres = []

    for lm in logMaterials:
        user = User.objects.filter(pk=lm.user_id).first()
        logMres.append(
            {
                "m_name": lm.m_name,
                "ml_i_id": int(lm.ml_i_id),
                "ml_action": lm.ml_action,
                "ml_date": lm.ml_date_add.strftime("%d.%m.%Y в %H:%M:%S"),
                "user": user
            }
        )

    #пагинация
    paginator = Paginator (log_res, 5)

    page_number = request.GET.get("page")

    page_obj = paginator.get_page(page_number)

    #пагинация для материал логов
    paginator_material_log = Paginator(logMres, 5)
    page_number_material_log = request.GET.get("page_material_log")
    page_obj_material_log = paginator_material_log.get_page(page_number_material_log)


    #подсчет сколько статей на сайте
    info_count = len(Info.objects.all())
    #подсчет сколько материалов на сайте
    materials_count = len(Material.objects.all())

    return render(
        request=request, 
        template_name='wiki/index.html',
        context={
            "allInfoChapters": allInfoChapters,
            "logs": log_res,
            "logs_count": len(log_res),
            "page_obj": page_obj,
            "logMres": logMres,
            "logM_count": len(logMres),
            "page_obj_material_log": page_obj_material_log,
            "info_count": info_count,
            "materials_count": materials_count
        }
        )




#получить подразделы нашего раздела
@login_required
def InfoChapterDetails(request, ic_url: str) -> HttpResponse:


    #получение разделов сайта
    allInfoChapters = getAllInfoChapterWithSubSection()

    #информация конкретно о нашем разделе
    infoChapter : dict = {}

    #ищем наш раздел
    for ic in allInfoChapters:
        if ic['ic_url'] == ic_url:
            infoChapter = ic

    #определяем контекст
    context = {
        "allInfoChapters": allInfoChapters,
        "infoChapter": infoChapter
    }

    #воззвращаем HttpResponse
    return render(request=request, context=context, template_name="wiki/infoChapter.html")


#получить информацию о подразделе
@login_required
def InfoSubSectionDetails(request, ic_url: str, iss_url: str) -> HttpResponse:

    #получение разделов сайта
    allInfoChapters = getAllInfoChapterWithSubSection()


    
    #находим информацию о подразделе
    infoSubSection = get_object_or_404(InfoSubSection, iss_url=iss_url)

    #находим все статьи данного раздела
    infos = Info.objects.filter(infoSubSection__id=infoSubSection.id)

    #структурируем информацию о всех статьях данного подраздела
    result_infos : list = []


    for i in infos:
        try:
            img_url = i.i_img.url
        except:
            img_url = False

        result_infos.append({
            "i_id": i.id,
            "i_name": i.i_name,
            "i_img": img_url,
        })

    #воззвращаем HttpResponse
    return render(
        request=request, 
        context={
            "allInfoChapters": allInfoChapters,
            "iss_name": infoSubSection.iss_name,
            "iss_url": infoSubSection.iss_url,
            "iss_description": infoSubSection.iss_description,
            "ic_name": infoSubSection.infoChapter.ic_name,
            "ic_url": ic_url,
            "result_infos": result_infos
        },
        template_name="wiki/InfoSubSection.html"
        )


#получить статью
@login_required
def InfoDetails(request, ic_url: str, iss_url: str, i_id: int) -> HttpResponse:
    #получение разделов сайта
    allInfoChapters = getAllInfoChapterWithSubSection()

    #получаем статью на сайте по её индентификатору
    info = Info.objects.filter(id=i_id).first()

    #получаем все материалы к нашей статье
    materials = Material.objects.filter(info__id=i_id).order_by('-m_date_add')

    #пагинатор
    paginator = Paginator (materials, 5) #будет показывтьа 5 объектов на одной странице 
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    #структурируем информацию о всех материалах статьи
    result_materials : list = []
    for m in materials:
        result_materials.append({
            "m_name": m.m_name,
            "m_date_add": m.m_date_add.strftime("%d.%m.%Y"),
            "m_file": m.m_file.url
        })

    try:
        main_img = info.i_img.url
    except:
        main_img = False


    #теперь проверяем какой метод в запросе
    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES)
        post = form.save(commit=False)
        post.info = info
        if form.is_valid():

            #добавляем лог о том, что мы добавили материал к статье
            LogMaterials.objects.create(
                m_name=post.m_name, 
                ml_i_id=i_id, 
                ml_action="загружен",
                user_id = request.user.id
            )

            post.save()
            return redirect(request.META['HTTP_REFERER'])
    
    else:
        form = MaterialForm()
    
    #воззвращаем HttpResponse
    return render(
        request=request,
        context={
            "allInfoChapters": allInfoChapters,
            "i_id": i_id,
            "i_name": info.i_name,
            "i_img": main_img,
            "i_date_creation": info.i_date_creation.strftime("%d.%m.%Y"),
            "i_text": info.i_text,
            "materials": result_materials,
            "iss_url": iss_url,
            "ic_url": ic_url,
            "form": form,
            "page_obj": page_obj
        },
        template_name="wiki/Info.html"
    )


#удаление материала к записи
@login_required
def deleteMaterial(request,ic_url, iss_url, i_id, m_id):
    #получение разделов сайта
    allInfoChapters = getAllInfoChapterWithSubSection()

    material = get_object_or_404(Material, pk=m_id)

    info = get_object_or_404(Info, pk=i_id)

    if request.method == 'POST':
        Material.objects.get(pk=m_id).delete()

        #добавляем лог о том, что мы добавили материал к статье
        LogMaterials.objects.create(
            m_name=material.m_name, 
            ml_i_id=i_id, 
            ml_action="удалён",
            user_id = request.user.id
        )

        return HttpResponseRedirect(reverse("wiki:InfoDetails", args=(ic_url, iss_url, i_id)))

    return render(
        request=request,
        context={
            "allInfoChapters": allInfoChapters,
            "ic_url": ic_url,
            "iss_url": iss_url,
            "i_id": i_id,
            "m_id": m_id,
            "m_name": material.m_name,
            "m_date_add": material.m_date_add.strftime("%d.%m.%Y"),
            "m_file": material.m_file.url,
            "i_name": info.i_name
        },
        template_name="wiki/deleteMaterial.html"
    )

#функция предсталвения рещультатов поиска 
@login_required
def searh(request) -> HttpResponse:

src/PocketDungSite/wiki/templates/wiki/Info.html
{% extends 'wiki/base.html' %}
{% load static %}

{% block title %}
    Статья о {{ i_name}}
{% endblock %}



{% block content %}
<div id="back-link">
    {% comment %} идентификатор записи {% endcomment %}
    <input id="i_id-value" type="hidden" value={{ i_id }}></input>

    <div id="back-link">
        <a href="{% url 'wiki:InfoSubSectionDetails' ic_url iss_url %}" >&#8592; Назад к подразделу</a>
    </div>

    <h1 id="page-name"><span style="color: red">{{ i_name }}</span></h1>

    <h3>Дата создания: {{ i_date_creation }}</h3>

    <div id="block-info-main-img">
    {% if i_img %}
        <img id="info-main-img" src={{ i_img }} />

        <div id="open-info-main-img"><a target="_blank" href={{ i_img }}>Открыть картинку в полном размере</a></div>
    {% else %}
        <img id="info-main-img" src={% static 'wiki/notImg.svg'%}>
    {% endif %}
    </div>

    <h2 class="sub-titel">Описание:</h2>

    <a class="change-info-link" href="/admin/wiki/info/{{ i_id }}/change">редактировать статью</a>

    <div id="html-form-db">{{ i_text|safe }}</div>

    <h2 class="sub-titel">Материалы:</h2>

    <div class="info-materials">
        {% if materials %}

            <div class="materials-list">
                <ul>
                {% for m in page_obj %}
                {# Each "contact" is a Contact model object. #}
                    <li><a target="_blank" href="{{ m.m_file.url }}"><span>Название: </span> <span style="color: red;">{{ m.m_name }}</span> <span>Дата: </span> <span style="color: red;">{{m.m_date_add}}</span></a> <a href="{% url 'wiki:deleteMaterial' ic_url iss_url i_id m.pk %}" class="delete-btn">Удалить</a></li>
                {% endfor %}
                </ul>
            </div>
        
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; первая</a>
                        <a href="?page={{ page_obj.previous_page_number }}">назад</a>
                    {% endif %}
            
                    <span class="current">
                        СТРАНИЦА {{ page_obj.number }} ИЗ {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">вперёд</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                    {% endif %}
                </span>
            </div>

            </ul>
        {% else %}
            К это статье материалов к игре пока нет.
        {% endif %}

        {% comment %} форма для добавления материала {% endcomment %}
        <div class="form-add-material">
            <form  enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <fieldset >
                    <legend><h2 class="sub-title-add">Добавить материал</h2></legend>
                    {{ form.as_p }}
                </fieldset>

                <input class="submit-btn" type="submit" value="Добавить материал">

            </form>
        </div>

    </div>
</div>

{% comment %} для сохранения значения scroll {% endcomment %}
<script type="text/javascript">
    {% comment %} получаем id со скрытого элемента {% endcomment %}
    var i_id = document.getElementById('i_id-value').value

    var scrollValue = sessionStorage.getItem(i_id)
    
    if (scrollValue) {
        window.scrollBy(0, scrollValue)
    }

    window.addEventListener('scroll', function () {
        sessionStorage.setItem(i_id, window.pageYOffset)
      });
</script>

{% endblock %}

src/PocketDungSite/wiki/templates/wiki/InfoSubSection.html
{% extends 'wiki/base.html' %}
{% load static %}

{% block title %}
    Подраздел {{ iss_name }}
{% endblock %}


{% block content %}
    <div id="back-link">
        <a href="{% url 'wiki:InfoChapterDetails' ic_url %}" >&#8592; Назад к разделу: <span style='color:red;'>{{ic_name}}</span></a>
    </div>

    <h1 id="page-name">Подраздел WIKI: <span style="color: red">{{ iss_name }}</span></h1>

    <div id="iss_description">{{iss_description}}</div>

    <h2 class="sub-titel">Его статьи:</h2>

    {% if result_infos %}
        <div class="infos-row">
            {% for ri in result_infos %}
                <div class="block-info">
                    <a href="{% url 'wiki:InfoDetails' ic_url iss_url ri.i_id  %}">
                    {% if ri.i_img%}
                        <div><img class='preview-img-info' src="{{ ri.i_img }}"></div>
                    {% else %}
                        <div><img class='preview-img-info' src={% static 'wiki/notImg.svg' %}></div>
                    {% endif %}

                    <div class="block-info-label">{{ ri.i_name }}</div>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p style="margin-bottom:10px;">На данный момент у этого подраздела, нет статей</p>

        <p style="margin-bottom:10px;">Чтобы создать их, необходимо перейти в Админ Панель</p>

        <p style="margin-bottom:10px;">Если вы не в курсе, как это делать, то советую перейти в раздел <a href='{% url 'wiki:InfoChapterDetails' 'instructions' %}'>Инструкции<a/> </p>
    {% endif %}
{% endblock %}

src/PocketDungSite/wiki/templates/wiki/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "ru">
    <head>
        <link rel="icon" href= {% static 'wiki/favicon.ico' %}><!-- 32×32 -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PocketDung Wiki - {% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel = "stylesheet" href = {% static 'wiki/style.css' %} type = "text/css">
    </head>
    <body>
        <nav>
            <div id="nav-logo">
                <img src={% static 'wiki/logo64x64.svg' %}>
            </div>

            <div id="name-site"> 
                <a href="{% url 'wiki:index' %}">
                    <div>WIKI</div>
                    <div>PocketDung</div>
                </a>
            </div>

            <div id="nav-links">
                {% for ic in allInfoChapters %}
                    <a href="{% url 'wiki:InfoChapterDetails' ic.ic_url %}" >{{ ic.ic_name }}</a>
                {% endfor %}
            </div>

            <div id="admin-panel"> 
                <a target="_blank" href="/admin">
                    <div>Админ</div>
                    <div>Панель</div>
                </a>
            </div>

            <div id="user-block">
            {% if request.user.is_authenticated  %}
                <div id="user-name">{{ request.user }}</div>
                <div><a href="{% url 'wiki:logout' %}" id="user-exit">Выйти</a></div>
            {% endif %}
            </div>

            <div id="vertical-menu"> 
                &#9776;
            </div>

        </nav>

        {% comment %} строка для поиска {% endcomment %}
        <div class="search-input">
            <form action="{% url 'wiki:search' %}" method="GET">
                <div>
                <input id="search-input" type="text" name="q" placeholder="Шо надо?">
                <input id="search-btn" type="submit" value="Поиск"></input>
                </div>
            </form>
        </div>

        {% comment %} меню вертикальное {% endcomment %}
        <div id="vertical-links" class="vertical-links">
            {% for ic in allInfoChapters %}
                <div>
                    <a href="{% url 'wiki:InfoChapterDetails' ic.ic_url %}" >{{ ic.ic_name }}</a>
                </div>
            {% endfor %}

                <div>
                    <a href="/admin"> Админ Панель</a>
                </div>
        </div>

        {% comment %} main сайта {% endcomment %}
        <main class="content">
            {% block content %}

            {% endblock %}
        </main>


        {% comment %} подвал сайта {% endcomment %}
        <footer>
            <div id="footer-text">
            © PocketDung 2024  В душе не ебу, что с защитой прав
            </div>

            <div id="footer-text-small">
                © PocketDung 2024 
            </div>
        </footer>
    </body>

    <script>
        var menu_btn = document.getElementById('vertical-menu'); 

        menu_btn.onclick = function(){
            var links = document.getElementById('vertical-links');

            if (links.className === "vertical-links"){
                links.className +="-open";
            } else {
                links.className = "vertical-links"
            }
        }
    </script>
</html>

src/PocketDungSite/wiki/templates/wiki/deleteMaterial.html
{% extends 'wiki/base.html' %}

{% block title %}
    Удаление материала -  {{ m_name }}
{% endblock %}

{% block content %}
    <h1 id="page-name"><span style="color: red">Вы точно хотите удалить данный материал?</span></h1>
    <h3><span style="color: red;">Название:</span> {{m_name}} <span style="color: red;">добавленный</span> {{m_date_add}} <span style="color: red;">к статье</span style="color: red;"> {{ i_name }} <h3>

    <div class="choise-delete-material">
        {% comment %} отказ от удлаения и возвращение на страницу со статьёй {% endcomment %}
        <div class="delete-btns">
            <a class="cancel-delete-btn" href="{% url 'wiki:InfoDetails' ic_url iss_url i_id %}">Не-е-ет, не надо дядя!</a>
        </div>

        <div class="delete-btns">
            {% comment %} соглашение с этим и удаление статьи {% endcomment %}
            <form action="{% url 'wiki:deleteMaterial' ic_url iss_url i_id m_id %}" method="POST">
                {% csrf_token %}
                <input class="submit-delete-btn" type="submit" value="Да, удаляем!">
            </form>
        </div>
    </div>
{% endblock %}

src/PocketDungSite/wiki/templates/wiki/infoChapter.html
{% extends 'wiki/base.html' %}


{% block title %}
    Раздел {{ infoChapter.ic_name}}
{% endblock %}


{% block content %}
    <h1 id="page-name">Раздел WIKI: <span style="color: red">{{infoChapter.ic_name}}</span></h1>

    <h2 class="sub-titel">Его подразделы:</h2>

    {% if infoChapter.ic_subs %}
        <ul>
            {% for ic_sub in infoChapter.ic_subs %}
                <li> <a href="{% url 'wiki:InfoSubSectionDetails' infoChapter.ic_url ic_sub.iss_url %}" >{{ ic_sub.iss_name }}</a> </li>
            {% endfor %}
        <ul>
    {% else %}
        <p style="margin-bottom:10px;">На данный момент у этого раздела, нет подразделов</p>

        <p style="margin-bottom:10px;">Чтобы создать их, необходимо перейти в Админ Панель</p>

        <p style="margin-bottom:10px;">Если вы не в курсе, как это делать, то советую перейти в раздел <a href='{% url 'wiki:InfoChapterDetails' 'instructions' %}'>Инструкции<a/> </p>
    {% endif %}

{% endblock %}

src/PocketDungSite/wiki/templates/wiki/login.html
{% load static %}
<!DOCTYPE html>
<html lang = "ru">
    <head>
        <link rel="icon" href= {% static 'wiki/favicon.ico' %}><!-- 32×32 -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>PocketDung Wiki - Вход</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel = "stylesheet" href = {% static 'wiki/login.css' %} type = "text/css">
    </head>
    <body>
        <div class="login-card">

            <div class="login-card-logo-block">
                <div class="login-card-logo-block-img">
                    <img src={% static 'wiki/logo64x64.svg' %}>
                </div>
                <div class="login-card-logo-block-label">
                    <div>WIKI</div>
                    <div>PocketDung</div>
                </div>
            </div>

            <div class="login-card-form">
                <form  action="{% url 'wiki:login'%}" method="post">
                    {% csrf_token %}
                    <input name="login" class="login-card-form-input" id="login" type="text" placeholder="Логин">
                    <input name="password" class="login-card-form-input" id="password" type="password" placeholder="Пароль">
                    <input id="submit" type="submit" value="Войти">
                </form>
            </div> 
        </div>
    </body>
</html>

src/PocketDungSite/wiki/templates/wiki/search_result.html
{% extends 'wiki/base.html' %}

{% block title %}
    Резлуьтат поиска по {{ searh_query }}
{% endblock %}


{% block content %}
    <h1 id="page-name">Результаты поиска по <span style="color: red;">{{ searh_query }}</span></h1>

    <div class="search-block">
    {% if results_info %}
        {% for i in results_info %}
        <a href="{% url 'wiki:result_search' i.id %}">
            <div class="search-card">
                <div class="search-card-title">{{ i.i_name }}</div>
                <div class="search-card-discreption">{{ i.i_text }}</div>
            </div>
        </a>
        {% endfor %}
    {% else %}
        <p>По вашему запросу нихуя нет...</p>
    {% endif %}
    </div>
{% endblock %}